name: example-stack-spot-template
description: Just a example of a template
types:
  - app-template
inputs:
  - label: Project name
    type: text
    name: project_name
    default: project-name
    global: true
  - label: "GroupId"
    type: text
    name: "group_id"
    default: "com.example"
    global: true